swagger: '2.0'


info:
  version: "0.0.1"
  title: BungieNetApi

schemes: [https]

          
definitions:
  PlayerSearchResponse:
    allOf:
      - properties:
          Response:
            type: array
            items:
              $ref: "#/definitions/PlayerSearchResult"
      - $ref: "#/definitions/BungieResponseBoilerplate"
  PlayerSearchResult:
    properties:
      iconPath:
        type: string
      membershipType:
        type: integer
        format: int32
        description: XBL (1) or PSN (2)
      membershipId:
        type: string
        description: The Destiny Membership ID
      displayName:
        type: string
        
  BungieResponseBoilerplate:
    properties:
      ErrorCode:
        type: integer
      ErrorStatus:
        type: string
        description: Error enum value
      Message:
        type: string
      MessageData:
        type: string
      ThrottleSeconds:
        type: integer      
            
paths:

  /Destiny/{membershipType}/Account/{destinyMembershipId}/Summary/:

    get:

      description: |
        Returns Destiny account information for the supplied membership.

      parameters:
        - $ref: "#/parameters/BungieNetApiKey"
        - $ref: "#/parameters/MembershipType"
        - $ref: "#/parameters/GetDefinitions"
        -
          name: destinyMembershipId
          in: path
          description: A valid Destiny Membership Id.
          required: true
          type: number
          
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          
  /SearchDestinyPlayer/{membershipType}/{username}/:
    get:
      description: Search for a player
      parameters:
        - $ref: "#/parameters/BungieNetApiKey"
        - $ref: "#/parameters/MembershipType"
        - 
          name: username
          in: path
          description: Gamertag or PSN ID to search for
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
                $ref: '#/definitions/PlayerSearchResponse'


parameters:
  BungieNetApiKey:
    name: x-api-key
    in: header
    description: BungieNet API Key
    required: true
    type: string    
  
  MembershipType:
    name: membershipType
    in: path
    description: XBL(1) or PSN(2)
    required: true
    type: integer
    enum: [1,2]
    format: int32
  
  GetDefinitions:
    name: definitions
    in: query
    description: Include definitions, use for debugging. 
    type: boolean