# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: BungieNetApi

schemes: [https]

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /Destiny/{membershipType}/Account/{destinyMembershipId}/:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Returns Destiny account information for the supplied membership.
      # This is array of GET operation parameters:
      parameters:
        # An example parameter that is in query and is required
        -
          name: x-api-key
          in: header
          description: BungieNet API Key
          required: true
          type: string
        -
          name: membershipType
          in: path
          description: XBL(1) or PSN(2)
          required: true
          type: integer
          format: int32
        -
          name: destinyMembershipId
          in: path
          description: A valid Destiny Membership Id.
          required: true
          type: number
          
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: ArrayOfPersons
            type: array
            items:
              title: Person
              type: object
              properties:
                name:
                  type: string
                single:
                  type: boolean